/**
 * Auto-generated Zod schemas from Prisma schema.
 * Generated by omni-rest — do not edit manually.
 * Re-run after schema changes.
 */
import { z } from "zod";

// ─── User ──────────────────────────────────────────────────────────────────

export const UserCreateSchema = z.object({
  id: z.string().optional(),
  email: z.string().optional(),
  name: z.string().optional(),
  phone: z.string().optional(),
  role: z.any().optional(),
  isActive: z.boolean().optional(),
  emailVerified: z.boolean().optional(),
  avatarUrl: z.string().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const UserUpdateSchema = UserCreateSchema.partial();

export type UserCreate = z.infer<typeof UserCreateSchema>;
export type UserUpdate = z.infer<typeof UserUpdateSchema>;

// ─── Address ──────────────────────────────────────────────────────────────────

export const AddressCreateSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  label: z.string().optional(),
  line1: z.string().optional(),
  line2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postalCode: z.string().optional(),
  country: z.string().optional(),
  isDefault: z.boolean().optional(),
  createdAt: z.coerce.date().optional(),
});

export const AddressUpdateSchema = AddressCreateSchema.partial();

export type AddressCreate = z.infer<typeof AddressCreateSchema>;
export type AddressUpdate = z.infer<typeof AddressUpdateSchema>;

// ─── Category ──────────────────────────────────────────────────────────────────

export const CategoryCreateSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.string().optional(),
  imageUrl: z.string().optional(),
  parentId: z.string().optional(),
  isActive: z.boolean().optional(),
  sortOrder: z.number().int().optional(),
  createdAt: z.coerce.date().optional(),
});

export const CategoryUpdateSchema = CategoryCreateSchema.partial();

export type CategoryCreate = z.infer<typeof CategoryCreateSchema>;
export type CategoryUpdate = z.infer<typeof CategoryUpdateSchema>;

// ─── Brand ──────────────────────────────────────────────────────────────────

export const BrandCreateSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  logoUrl: z.string().optional(),
  website: z.string().optional(),
  isActive: z.boolean().optional(),
  createdAt: z.coerce.date().optional(),
});

export const BrandUpdateSchema = BrandCreateSchema.partial();

export type BrandCreate = z.infer<typeof BrandCreateSchema>;
export type BrandUpdate = z.infer<typeof BrandUpdateSchema>;

// ─── Product ──────────────────────────────────────────────────────────────────

export const ProductCreateSchema = z.object({
  id: z.string().optional(),
  sku: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.string().optional(),
  price: z.number().optional(),
  comparePrice: z.number().optional(),
  costPrice: z.number().optional(),
  categoryId: z.string().optional(),
  brandId: z.string().optional(),
  isActive: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
  weight: z.number().optional(),
  tags: z.string().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const ProductUpdateSchema = ProductCreateSchema.partial();

export type ProductCreate = z.infer<typeof ProductCreateSchema>;
export type ProductUpdate = z.infer<typeof ProductUpdateSchema>;

// ─── Variant ──────────────────────────────────────────────────────────────────

export const VariantCreateSchema = z.object({
  id: z.string().optional(),
  productId: z.string().optional(),
  sku: z.string().optional(),
  name: z.string().optional(),
  price: z.number().optional(),
  stockQty: z.number().int().optional(),
  attributes: z.any().optional(),
  isActive: z.boolean().optional(),
  createdAt: z.coerce.date().optional(),
});

export const VariantUpdateSchema = VariantCreateSchema.partial();

export type VariantCreate = z.infer<typeof VariantCreateSchema>;
export type VariantUpdate = z.infer<typeof VariantUpdateSchema>;

// ─── ProductImage ──────────────────────────────────────────────────────────────────

export const ProductImageCreateSchema = z.object({
  id: z.string().optional(),
  productId: z.string().optional(),
  url: z.string().optional(),
  altText: z.string().optional(),
  sortOrder: z.number().int().optional(),
  isPrimary: z.boolean().optional(),
});

export const ProductImageUpdateSchema = ProductImageCreateSchema.partial();

export type ProductImageCreate = z.infer<typeof ProductImageCreateSchema>;
export type ProductImageUpdate = z.infer<typeof ProductImageUpdateSchema>;

// ─── StockMovement ──────────────────────────────────────────────────────────────────

export const StockMovementCreateSchema = z.object({
  id: z.string().optional(),
  variantId: z.string().optional(),
  type: z.any().optional(),
  quantity: z.number().int().optional(),
  reference: z.string().optional(),
  note: z.string().optional(),
  createdAt: z.coerce.date().optional(),
});

export const StockMovementUpdateSchema = StockMovementCreateSchema.partial();

export type StockMovementCreate = z.infer<typeof StockMovementCreateSchema>;
export type StockMovementUpdate = z.infer<typeof StockMovementUpdateSchema>;

// ─── Cart ──────────────────────────────────────────────────────────────────

export const CartCreateSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const CartUpdateSchema = CartCreateSchema.partial();

export type CartCreate = z.infer<typeof CartCreateSchema>;
export type CartUpdate = z.infer<typeof CartUpdateSchema>;

// ─── CartItem ──────────────────────────────────────────────────────────────────

export const CartItemCreateSchema = z.object({
  id: z.string().optional(),
  cartId: z.string().optional(),
  productId: z.string().optional(),
  variantId: z.string().optional(),
  quantity: z.number().int().optional(),
  addedAt: z.coerce.date().optional(),
});

export const CartItemUpdateSchema = CartItemCreateSchema.partial();

export type CartItemCreate = z.infer<typeof CartItemCreateSchema>;
export type CartItemUpdate = z.infer<typeof CartItemUpdateSchema>;

// ─── WishlistItem ──────────────────────────────────────────────────────────────────

export const WishlistItemCreateSchema = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  productId: z.string().optional(),
  addedAt: z.coerce.date().optional(),
});

export const WishlistItemUpdateSchema = WishlistItemCreateSchema.partial();

export type WishlistItemCreate = z.infer<typeof WishlistItemCreateSchema>;
export type WishlistItemUpdate = z.infer<typeof WishlistItemUpdateSchema>;

// ─── Order ──────────────────────────────────────────────────────────────────

export const OrderCreateSchema = z.object({
  id: z.string().optional(),
  orderNumber: z.string().optional(),
  userId: z.string().optional(),
  addressId: z.string().optional(),
  status: z.any().optional(),
  paymentStatus: z.any().optional(),
  paymentMethod: z.any().optional(),
  subtotal: z.number().optional(),
  discountAmount: z.number().optional(),
  shippingAmount: z.number().optional(),
  taxAmount: z.number().optional(),
  total: z.number().optional(),
  notes: z.string().optional(),
  couponCode: z.string().optional(),
  placedAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const OrderUpdateSchema = OrderCreateSchema.partial();

export type OrderCreate = z.infer<typeof OrderCreateSchema>;
export type OrderUpdate = z.infer<typeof OrderUpdateSchema>;

// ─── OrderItem ──────────────────────────────────────────────────────────────────

export const OrderItemCreateSchema = z.object({
  id: z.string().optional(),
  orderId: z.string().optional(),
  productId: z.string().optional(),
  variantId: z.string().optional(),
  productName: z.string().optional(),
  variantName: z.string().optional(),
  sku: z.string().optional(),
  quantity: z.number().int().optional(),
  unitPrice: z.number().optional(),
  totalPrice: z.number().optional(),
});

export const OrderItemUpdateSchema = OrderItemCreateSchema.partial();

export type OrderItemCreate = z.infer<typeof OrderItemCreateSchema>;
export type OrderItemUpdate = z.infer<typeof OrderItemUpdateSchema>;

// ─── Payment ──────────────────────────────────────────────────────────────────

export const PaymentCreateSchema = z.object({
  id: z.string().optional(),
  orderId: z.string().optional(),
  method: z.any().optional(),
  amount: z.number().optional(),
  currency: z.string().optional(),
  status: z.any().optional(),
  transactionId: z.string().optional(),
  gatewayRef: z.string().optional(),
  paidAt: z.coerce.date().optional(),
  createdAt: z.coerce.date().optional(),
});

export const PaymentUpdateSchema = PaymentCreateSchema.partial();

export type PaymentCreate = z.infer<typeof PaymentCreateSchema>;
export type PaymentUpdate = z.infer<typeof PaymentUpdateSchema>;

// ─── Shipment ──────────────────────────────────────────────────────────────────

export const ShipmentCreateSchema = z.object({
  id: z.string().optional(),
  orderId: z.string().optional(),
  carrier: z.string().optional(),
  trackingNumber: z.string().optional(),
  shippedAt: z.coerce.date().optional(),
  estimatedAt: z.coerce.date().optional(),
  deliveredAt: z.coerce.date().optional(),
  createdAt: z.coerce.date().optional(),
});

export const ShipmentUpdateSchema = ShipmentCreateSchema.partial();

export type ShipmentCreate = z.infer<typeof ShipmentCreateSchema>;
export type ShipmentUpdate = z.infer<typeof ShipmentUpdateSchema>;

// ─── Review ──────────────────────────────────────────────────────────────────

export const ReviewCreateSchema = z.object({
  id: z.string().optional(),
  productId: z.string().optional(),
  userId: z.string().optional(),
  rating: z.number().int().optional(),
  title: z.string().optional(),
  body: z.string().optional(),
  isVerified: z.boolean().optional(),
  isApproved: z.boolean().optional(),
  createdAt: z.coerce.date().optional(),
});

export const ReviewUpdateSchema = ReviewCreateSchema.partial();

export type ReviewCreate = z.infer<typeof ReviewCreateSchema>;
export type ReviewUpdate = z.infer<typeof ReviewUpdateSchema>;

// ─── Coupon ──────────────────────────────────────────────────────────────────

export const CouponCreateSchema = z.object({
  id: z.string().optional(),
  code: z.string().optional(),
  description: z.string().optional(),
  discountPercent: z.number().optional(),
  discountAmount: z.number().optional(),
  minOrderValue: z.number().optional(),
  maxUses: z.number().int().optional(),
  usedCount: z.number().int().optional(),
  isActive: z.boolean().optional(),
  expiresAt: z.coerce.date().optional(),
  createdAt: z.coerce.date().optional(),
});

export const CouponUpdateSchema = CouponCreateSchema.partial();

export type CouponCreate = z.infer<typeof CouponCreateSchema>;
export type CouponUpdate = z.infer<typeof CouponUpdateSchema>;
