import type { GeneratorConfig } from "../types";

export function generateMenuData(config: GeneratorConfig): string {
  const { models } = config;
  const items = models.map((mc) => {
    const { name } = mc.model;
    return `  { label: '${name}s', href: '/${name.toLowerCase()}s' },`;
  });

  return [
    `/** Auto-generated by omni-rest-client — do not edit manually. */`,
    ``,
    `export interface MenuItem { label: string; href: string; icon?: string; }`,
    ``,
    `export const omniRestMenuItems: MenuItem[] = [`,
    ...items,
    `];`,
    ``,
  ].join("\n");
}
