/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Departments */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description e.g. createdAt:desc */
                    sort?: string;
                    /** @description Comma-separated relations */
                    include?: string;
                    /** @description Comma-separated fields */
                    select?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Departments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create Department */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentCreate"];
                };
            };
            responses: {
                /** @description Created Department */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/department/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Department ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Department by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Department ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Department record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update Department */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Department ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentCreate"];
                };
            };
            responses: {
                /** @description Updated Department */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete Department */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Department ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Partially update Department */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Department ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentUpdate"];
                };
            };
            responses: {
                /** @description Updated Department */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/department/bulk/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk update Departments */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of Department objects with id field to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentUpdate"][];
                };
            };
            responses: {
                /** @description Bulk update result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: number;
                            records?: components["schemas"]["Department"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/api/department/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Bulk delete Departments */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of IDs to delete */
            requestBody: {
                content: {
                    "application/json": string[];
                };
            };
            responses: {
                /** @description Bulk delete result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categorys */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description e.g. createdAt:desc */
                    sort?: string;
                    /** @description Comma-separated relations */
                    include?: string;
                    /** @description Comma-separated fields */
                    select?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Categorys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create Category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreate"];
                };
            };
            responses: {
                /** @description Created Category */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Category by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Category ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update Category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Category ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreate"];
                };
            };
            responses: {
                /** @description Updated Category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete Category */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Category ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Partially update Category */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Category ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryUpdate"];
                };
            };
            responses: {
                /** @description Updated Category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/category/bulk/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk update Categorys */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of Category objects with id field to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryUpdate"][];
                };
            };
            responses: {
                /** @description Bulk update result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: number;
                            records?: components["schemas"]["Category"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/api/category/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Bulk delete Categorys */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of IDs to delete */
            requestBody: {
                content: {
                    "application/json": string[];
                };
            };
            responses: {
                /** @description Bulk delete result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description e.g. createdAt:desc */
                    sort?: string;
                    /** @description Comma-separated relations */
                    include?: string;
                    /** @description Comma-separated fields */
                    select?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Product"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create Product */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCreate"];
                };
            };
            responses: {
                /** @description Created Product */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get Product by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update Product */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCreate"];
                };
            };
            responses: {
                /** @description Updated Product */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete Product */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Partially update Product */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductUpdate"];
                };
            };
            responses: {
                /** @description Updated Product */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/product/bulk/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk update Products */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of Product objects with id field to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductUpdate"][];
                };
            };
            responses: {
                /** @description Bulk update result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: number;
                            records?: components["schemas"]["Product"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/api/product/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Bulk delete Products */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of IDs to delete */
            requestBody: {
                content: {
                    "application/json": string[];
                };
            };
            responses: {
                /** @description Bulk delete result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Citys */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description e.g. createdAt:desc */
                    sort?: string;
                    /** @description Comma-separated relations */
                    include?: string;
                    /** @description Comma-separated fields */
                    select?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Citys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["City"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create City */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CityCreate"];
                };
            };
            responses: {
                /** @description Created City */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/city/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description City ID */
                id: string;
            };
            cookie?: never;
        };
        /** Get City by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description City ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description City record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update City */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description City ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CityCreate"];
                };
            };
            responses: {
                /** @description Updated City */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete City */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description City ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Partially update City */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description City ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CityUpdate"];
                };
            };
            responses: {
                /** @description Updated City */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["City"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/city/bulk/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk update Citys */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of City objects with id field to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CityUpdate"][];
                };
            };
            responses: {
                /** @description Bulk update result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: number;
                            records?: components["schemas"]["City"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/api/city/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Bulk delete Citys */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Array of IDs to delete */
            requestBody: {
                content: {
                    "application/json": string[];
                };
            };
            responses: {
                /** @description Bulk delete result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Department: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DepartmentCreate: {
            name: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DepartmentUpdate: {
            name?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Category: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: int32 */
            departmentId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CategoryCreate: {
            name: string;
            /** Format: int32 */
            departmentId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CategoryUpdate: {
            name?: string;
            /** Format: int32 */
            departmentId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Product: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: float */
            price?: number;
            /** Format: int32 */
            categoryId?: number;
            /** Format: int32 */
            cityId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProductCreate: {
            name: string;
            /** Format: float */
            price: number;
            /** Format: int32 */
            categoryId: number;
            /** Format: int32 */
            cityId?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProductUpdate: {
            name?: string;
            /** Format: float */
            price?: number;
            /** Format: int32 */
            categoryId?: number;
            /** Format: int32 */
            cityId?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        City: {
            /** Format: int32 */
            id?: number;
            name?: string;
            country?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CityCreate: {
            name: string;
            country: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CityUpdate: {
            name?: string;
            country?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PaginationMeta: {
            total?: number;
            page?: number;
            limit?: number;
            totalPages?: number;
        };
        Error: {
            error?: string;
        };
    };
    responses: {
        /** @description Record not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unique constraint violation */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
