/**
 * Auto-generated Zod schemas from Prisma schema.
 * Generated by omni-rest — do not edit manually.
 * Re-run after schema changes.
 */
import { z } from "zod";

// ─── Department ──────────────────────────────────────────────────────────────────

export const DepartmentCreateSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const DepartmentUpdateSchema = DepartmentCreateSchema.partial();

export type DepartmentCreate = z.infer<typeof DepartmentCreateSchema>;
export type DepartmentUpdate = z.infer<typeof DepartmentUpdateSchema>;

// ─── Category ──────────────────────────────────────────────────────────────────

export const CategoryCreateSchema = z.object({
  name: z.string(),
  departmentId: z.number().int(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const CategoryUpdateSchema = CategoryCreateSchema.partial();

export type CategoryCreate = z.infer<typeof CategoryCreateSchema>;
export type CategoryUpdate = z.infer<typeof CategoryUpdateSchema>;

// ─── Product ──────────────────────────────────────────────────────────────────

export const ProductCreateSchema = z.object({
  name: z.string(),
  price: z.number(),
  categoryId: z.number().int(),
  cityId: z.number().int().optional(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const ProductUpdateSchema = ProductCreateSchema.partial();

export type ProductCreate = z.infer<typeof ProductCreateSchema>;
export type ProductUpdate = z.infer<typeof ProductUpdateSchema>;

// ─── City ──────────────────────────────────────────────────────────────────

export const CityCreateSchema = z.object({
  name: z.string(),
  country: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const CityUpdateSchema = CityCreateSchema.partial();

export type CityCreate = z.infer<typeof CityCreateSchema>;
export type CityUpdate = z.infer<typeof CityUpdateSchema>;
