import type { ModelMeta } from "../types";

// The resolved, validated configuration for a single generation run
export interface GeneratorConfig {
  frontendDir: string;
  schemaPath: string;
  framework: "nextjs" | "vite-react" | "react";
  baseUrl: string;
  outputDir: string;
  autopilot: boolean;
  models: ModelConfig[];
  staleTime: number;
  gcTime: number;
  noOptimistic: boolean;
  steps: "auto" | "always" | "never";
  generatePages?: boolean;      // Generate Next.js pages (default: true for Next.js)
  generateMenu?: boolean;        // Generate menu-data.ts (default: true)
  routeGroup?: string;           // Route group name (default: "autogenerated-omni")
}

// Per-model configuration resolved from prompts or autopilot defaults
export interface ModelConfig {
  model: ModelMeta;
  tableFields: string[];      // scalar field names to show in table
  formFields: string[];       // scalar field names to show in form
  relationalFields: string[]; // relational field names to render as searchable-select
  bulkDelete: boolean;
  canExport: boolean;
  multiStep: boolean;
}

// Result of writing a single file
export interface FileResult {
  path: string;
  status: "created" | "overwritten" | "skipped" | "error";
  error?: Error;
}

// Candidate frontend directory with scoring
export interface CandidateFrontend {
  dir: string;       // absolute path
  score: number;
  signals: string[]; // human-readable reasons, e.g. ["next.config.js found"]
}
