#!/usr/bin/env node
/**
 * omni-rest-client CLI
 *
 * Usage:
 *   npx omni-rest-client generate:frontend   → scaffold frontend from omni-rest.config.json
 *
 * Requires omni-rest.config.json generated by:
 *   npx omni-rest generate:config
 */

import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import { loadConfig, buildAutopilotModelConfigs, generateAll, detectProjectStructure } from "./generator";
import type { GeneratorConfig } from "./types";

const COLORS = {
  green:  (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  cyan:   (s: string) => `\x1b[36m${s}\x1b[0m`,
  red:    (s: string) => `\x1b[31m${s}\x1b[0m`,
  bold:   (s: string) => `\x1b[1m${s}\x1b[0m`,
};

const args = process.argv.slice(2);
const command = args[0] ?? "generate:frontend";
const cwd = process.cwd();

const USAGE = `
  Usage:
    npx omni-rest-client generate:frontend   Scaffold frontend from omni-rest.config.json

  Options:
    --config <path>         Path to omni-rest.config.json (default: ./omni-rest.config.json)
    --frontend-dir <path>   Frontend project root (default: cwd)
    --out <dir>             Output directory relative to frontend-dir (default: src/ or root)
    --models <names>        Comma-separated model names to generate (default: all)
    --base-url <url>        API base URL (default: /api)
    --framework <name>      nextjs | vite-react | react (default: auto-detect)
    --autopilot             Skip all prompts, use defaults
    --no-bulk               Disable bulk delete
    --no-optimistic         Disable optimistic updates
    --no-pages              Disable Next.js page generation
    --no-menu               Disable menu-data.ts generation
    --route-group <name>    Route group name (default: autogenerated-omni)
    --stale-time <ms>       useQuery staleTime (default: 30000)
    --gc-time <ms>          useQuery gcTime (default: 300000)
    --steps <mode>          auto | always | never (default: auto)
    --write-schemas         Also write schemas.generated.ts from config (default: true)
    --help                  Print this help
`;

function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(question, (a) => { rl.close(); resolve(a.trim()); }));
}

function detectFramework(dir: string): "nextjs" | "vite-react" | "react" {
  if (fs.existsSync(path.join(dir, "next.config.js")) || fs.existsSync(path.join(dir, "next.config.ts"))) return "nextjs";
  if (fs.existsSync(path.join(dir, "vite.config.ts")) || fs.existsSync(path.join(dir, "vite.config.js"))) return "vite-react";
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf-8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if ("react" in deps) return "react";
  } catch { /* ignore */ }
  return "react";
}

function resolveOutputDir(frontendDir: string): string {
  if (fs.existsSync(path.join(frontendDir, "src"))) return path.join(frontendDir, "src");
  return frontendDir;
}

async function run() {
  console.log(COLORS.bold("\n  omni-rest-client · generate:frontend\n"));

  if (args.includes("--help") || command === "help") {
    console.log(USAGE);
    return;
  }

  if (command !== "generate:frontend") {
    console.log(USAGE);
    return;
  }

  // ── Parse flags ────────────────────────────────────────────────────────────
  let configPath = path.resolve(cwd, "omni-rest.config.json");
  let frontendDirFlag: string | undefined;
  let outFlag: string | undefined;
  let modelsFlag: string | undefined;
  let baseUrlFlag: string | undefined;
  let frameworkFlag: string | undefined;
  let autopilot = false;
  let noBulk = false;
  let noOptimistic = false;
  let generatePages = true;
  let generateMenu = true;
  let routeGroup = "autogenerated-omni";
  let staleTime = 30000;
  let gcTime = 300000;
  let stepsFlag: "auto" | "always" | "never" = "auto";
  let writeSchemas = true;

  for (let i = 1; i < args.length; i++) {
    switch (args[i]) {
      case "--config":        configPath = path.resolve(cwd, args[++i]); break;
      case "--frontend-dir":  frontendDirFlag = args[++i]; break;
      case "--out":           outFlag = args[++i]; break;
      case "--models":        modelsFlag = args[++i]; break;
      case "--base-url":      baseUrlFlag = args[++i]; break;
      case "--framework":     frameworkFlag = args[++i]; break;
      case "--autopilot":     autopilot = true; break;
      case "--no-bulk":       noBulk = true; break;
      case "--no-optimistic": noOptimistic = true; break;
      case "--no-pages":      generatePages = false; break;
      case "--no-menu":       generateMenu = false; break;
      case "--no-schemas":    writeSchemas = false; break;
      case "--route-group":   routeGroup = args[++i]; break;
      case "--stale-time":    staleTime = parseInt(args[++i], 10) || 30000; break;
      case "--gc-time":       gcTime = parseInt(args[++i], 10) || 300000; break;
      case "--steps": {
        const v = args[++i];
        if (v === "always" || v === "never" || v === "auto") stepsFlag = v;
        break;
      }
    }
  }

  // ── Step 1: Load config ────────────────────────────────────────────────────
  let omniConfig;
  try {
    omniConfig = loadConfig(configPath);
    console.log(COLORS.cyan(`  → Config: ${configPath} (${omniConfig.models.length} models)`));
  } catch (err: any) {
    console.error(COLORS.red(`  ✗ ${err.message}`));
    process.exit(1);
  }

  // ── Step 2: Resolve frontend dir ───────────────────────────────────────────
  let frontendDir = frontendDirFlag ? path.resolve(cwd, frontendDirFlag) : cwd;
  if (!fs.existsSync(frontendDir)) {
    console.error(COLORS.red(`  ✗ Frontend dir not found: "${frontendDir}"`));
    process.exit(1);
  }

  if (!frontendDirFlag && !autopilot) {
    const answer = await prompt(`  Frontend dir: ${COLORS.bold(frontendDir)}\n  Use this directory? [Y/n]: `);
    if (answer.toLowerCase() === "n" || answer.toLowerCase() === "no") {
      console.log("  Aborted.");
      return;
    }
  }
  console.log(COLORS.cyan(`  → Frontend dir: ${frontendDir}`));

  // ── Step 3: Detect framework ───────────────────────────────────────────────
  const framework = (frameworkFlag as any) ?? detectFramework(frontendDir);
  console.log(COLORS.cyan(`  → Framework: ${framework}`));

  // ── Step 4: Resolve base URL ───────────────────────────────────────────────
  let baseUrl = baseUrlFlag ?? "/api";
  if (!baseUrlFlag) {
    // Try to read from env files
    for (const envFile of [".env.local", ".env"]) {
      try {
        const content = fs.readFileSync(path.join(frontendDir, envFile), "utf-8");
        const match = content.match(/(?:NEXT_PUBLIC_API_URL|VITE_API_URL)\s*=\s*["']?([^"'\n]+)["']?/);
        if (match) { baseUrl = match[1].trim(); break; }
      } catch { /* ignore */ }
    }
  }
  console.log(COLORS.cyan(`  → Base URL: ${baseUrl}`));

  // ── Step 5: Resolve output dir ─────────────────────────────────────────────
  const outputDir = outFlag ? path.resolve(frontendDir, outFlag) : resolveOutputDir(frontendDir);
  console.log(COLORS.cyan(`  → Output dir: ${outputDir}`));

  // ── Step 6: Write schemas.generated.ts ────────────────────────────────────
  if (writeSchemas && omniConfig.zodSchemas) {
    const schemasPath = path.join(outputDir, "schemas.generated.ts");
    fs.mkdirSync(path.dirname(schemasPath), { recursive: true });
    fs.writeFileSync(schemasPath, omniConfig.zodSchemas, "utf-8");
    console.log(COLORS.green(`  ✓ Written: ${schemasPath}`));
  }

  // ── Step 7: Build model configs ────────────────────────────────────────────
  const modelsFilter = modelsFlag?.split(",").map((s) => s.trim()).filter(Boolean);
  const modelConfigs = buildAutopilotModelConfigs(omniConfig.models, { noBulk, steps: stepsFlag, modelsFilter });

  // ── Step 8: Generate ───────────────────────────────────────────────────────
  const generatorConfig: GeneratorConfig = {
    configPath,
    frontendDir,
    framework,
    baseUrl,
    outputDir,
    autopilot,
    models: modelConfigs,
    staleTime,
    gcTime,
    noOptimistic,
    steps: stepsFlag,
    generatePages,
    generateMenu,
    routeGroup,
  };

  await generateAll(generatorConfig);
  console.log(COLORS.bold("\n  Done!\n"));

  // Print install command for all required dependencies
  const deps = [
    "@tanstack/react-query", "@tanstack/react-table",
    "react-hook-form", "zod", "@hookform/resolvers",
    "class-variance-authority", "clsx", "tailwind-merge", "lucide-react",
    "@radix-ui/react-alert-dialog", "@radix-ui/react-checkbox",
    "@radix-ui/react-dialog", "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-popover", "@radix-ui/react-progress",
    "@radix-ui/react-scroll-area", "@radix-ui/react-select",
    "@radix-ui/react-separator", "@radix-ui/react-slot",
    "@radix-ui/react-switch", "@radix-ui/react-tooltip",
    "cmdk", "react-day-picker",
  ];
  console.log(COLORS.yellow("  Install required dependencies:"));
  console.log(COLORS.cyan(`  npm install ${deps.join(" ")}\n`));
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
