import * as fs from "fs";
import * as path from "path";
import type { GeneratorConfig, ModelConfig, FileResult, OmniRestConfig, ModelMeta, FieldMeta } from "./types";
import { generateHookFile } from "./codegen/hook";
import { generateColumnsFile } from "./codegen/columns";
import { generateTableFile } from "./codegen/table";
import { generateFormFile } from "./codegen/form";
import { generatePageFile } from "./codegen/page";
import { generateMenuData } from "./codegen/menu";
import { generateProvidersFile } from "./codegen/providers";
import { writeFile, copyBaseComponents, printSummary } from "./output";

export type { GeneratorConfig, ModelConfig, FileResult, OmniRestConfig };

// ─── Project structure detection ─────────────────────────────────────────────

export interface ProjectStructure {
  usesAppRouter: boolean;
  appPath: string | null;
}

export function detectProjectStructure(frontendDir: string): ProjectStructure {
  const hasApp    = fs.existsSync(path.join(frontendDir, "app"));
  const hasSrcApp = fs.existsSync(path.join(frontendDir, "src", "app"));
  const usesAppRouter = hasApp || hasSrcApp;
  let appPath: string | null = null;
  if (hasSrcApp) appPath = path.join(frontendDir, "src", "app");
  else if (hasApp) appPath = path.join(frontendDir, "app");
  return { usesAppRouter, appPath };
}

// ─── Config loader ────────────────────────────────────────────────────────────

/**
 * Loads and validates omni-rest.config.json from the given path.
 */
export function loadConfig(configPath: string): OmniRestConfig {
  if (!fs.existsSync(configPath)) {
    throw new Error(
      `[omni-rest-client] Config file not found: "${configPath}"\n` +
      `Run "npx omni-rest generate:config" in your backend project first.`
    );
  }
  const raw = JSON.parse(fs.readFileSync(configPath, "utf-8"));
  if (!raw.models || !Array.isArray(raw.models)) {
    throw new Error(`[omni-rest-client] Invalid config file: missing "models" array.`);
  }
  return raw as OmniRestConfig;
}

// ─── Autopilot model config builder ──────────────────────────────────────────

function scalarFields(model: ModelMeta): FieldMeta[] {
  return model.fields.filter((f) => !f.isRelation);
}

function formEditableFields(model: ModelMeta): FieldMeta[] {
  return model.fields.filter((f) => !f.isRelation && !f.isId && !f.hasDefaultValue && !f.isUpdatedAt);
}

export function buildAutopilotModelConfigs(
  models: ModelMeta[],
  opts: { noBulk?: boolean; steps?: "auto" | "always" | "never"; modelsFilter?: string[] }
): ModelConfig[] {
  const filtered = opts.modelsFilter?.length
    ? models.filter((m) => opts.modelsFilter!.includes(m.name))
    : models;

  return filtered.map((model) => {
    const fieldCount = model.fields.length;
    let multiStep = fieldCount > 6;
    if (opts.steps === "always") multiStep = true;
    if (opts.steps === "never") multiStep = false;

    return {
      model,
      tableFields: scalarFields(model).map((f) => f.name),
      formFields: formEditableFields(model).map((f) => f.name),
      relationalFields: model.fields.filter((f) => f.isRelation).map((f) => f.name),
      bulkDelete: !opts.noBulk,
      canExport: true,
      multiStep,
    };
  });
}

// ─── Main generate orchestrator ───────────────────────────────────────────────

export async function generateAll(config: GeneratorConfig): Promise<FileResult[]> {
  const { outputDir, models, framework, frontendDir } = config;
  const generatePages = config.generatePages ?? (framework === "nextjs");
  const generateMenu  = config.generateMenu ?? true;
  const routeGroup    = config.routeGroup ?? "autogenerated-omni";
  const packageRoot   = path.resolve(__dirname, "..");

  const results: FileResult[] = [];
  const structure = detectProjectStructure(frontendDir);

  for (const modelConfig of models) {
    const { name } = modelConfig.model;
    const modelLower = name.charAt(0).toLowerCase() + name.slice(1);

    results.push(await writeFile(path.join(outputDir, "hooks", `use${name}.ts`), generateHookFile(config, modelConfig)));
    results.push(await writeFile(path.join(outputDir, "components", modelLower, `${name}Columns.tsx`), generateColumnsFile(config, modelConfig)));
    results.push(await writeFile(path.join(outputDir, "components", modelLower, `${name}Table.tsx`), generateTableFile(config, modelConfig)));
    results.push(await writeFile(path.join(outputDir, "components", modelLower, `${name}Form.tsx`), generateFormFile(config, modelConfig)));

    if (generatePages && framework === "nextjs" && structure.usesAppRouter && structure.appPath) {
      const pluralLower = name.toLowerCase() + "s";
      const pagePath = path.join(structure.appPath, `(${routeGroup})`, pluralLower, "page.tsx");
      results.push(await writeFile(pagePath, generatePageFile(config, modelConfig)));
    }
  }

  results.push(...await copyBaseComponents(outputDir, packageRoot));

  if (framework === "nextjs" && structure.usesAppRouter) {
    results.push(await writeFile(path.join(outputDir, "components", "providers.tsx"), generateProvidersFile(config)));
  }

  if (generateMenu) {
    results.push(await writeFile(path.join(outputDir, "lib", "menu-data.ts"), generateMenuData(config)));
  }

  printSummary(results);
  return results;
}
