import type { GeneratorConfig } from "../types";

/**
 * Generates menu-data.ts file with routes for all generated pages.
 * 
 * Example output:
 * ```typescript
 * export interface MenuItem {
 *   label: string;
 *   href: string;
 * }
 * 
 * export const omniRestMenuItems: MenuItem[] = [
 *   { label: 'Users', href: '/users' },
 *   { label: 'Products', href: '/products' },
 * ];
 * ```
 */
export function generateMenuData(config: GeneratorConfig): string {
  const { models } = config;

  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * Auto-generated menu data for omni-rest CRUD pages`);
  lines.push(` * Generated by omni-rest — do not edit manually.`);
  lines.push(` * Re-run after schema changes.`);
  lines.push(` */`);
  lines.push(``);

  // MenuItem interface
  lines.push(`export interface MenuItem {`);
  lines.push(`  label: string;`);
  lines.push(`  href: string;`);
  lines.push(`  icon?: string;`);
  lines.push(`}`);
  lines.push(``);

  // Generate menu items array
  lines.push(`export const omniRestMenuItems: MenuItem[] = [`);
  
  for (const modelConfig of models) {
    const { name } = modelConfig.model;
    const pluralName = name + "s"; // Simple pluralization
    const route = `/${name.toLowerCase()}s`;
    
    lines.push(`  {`);
    lines.push(`    label: '${pluralName}',`);
    lines.push(`    href: '${route}',`);
    lines.push(`  },`);
  }
  
  lines.push(`];`);
  lines.push(``);

  // Helper function to get menu by label
  lines.push(`/**`);
  lines.push(` * Get a menu item by its label`);
  lines.push(` */`);
  lines.push(`export function getMenuItemByLabel(label: string): MenuItem | undefined {`);
  lines.push(`  return omniRestMenuItems.find(item => item.label === label);`);
  lines.push(`}`);
  lines.push(``);

  // Helper function to get menu by href
  lines.push(`/**`);
  lines.push(` * Get a menu item by its href`);
  lines.push(` */`);
  lines.push(`export function getMenuItemByHref(href: string): MenuItem | undefined {`);
  lines.push(`  return omniRestMenuItems.find(item => item.href === href);`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
