import type { GeneratorConfig, ModelConfig } from "../types";

/**
 * Generates a Next.js App Router page.tsx file for a model.
 * 
 * Example output:
 * ```tsx
 * 'use client'
 * 
 * import { UserTable } from '@/components/user/UserTable'
 * 
 * export default function UsersPage() {
 *   return (
 *     <div className="container mx-auto py-10">
 *       <h1 className="text-3xl font-bold mb-6">Users</h1>
 *       <UserTable />
 *     </div>
 *   )
 * }
 * ```
 */
export function generatePageFile(
  config: GeneratorConfig,
  modelConfig: ModelConfig
): string {
  const { model } = modelConfig;
  const { name } = model;
  const modelLower = name.charAt(0).toLowerCase() + name.slice(1);
  const pluralName = name + "s"; // Simple pluralization

  const lines: string[] = [];

  // 'use client' directive (required for App Router with client components)
  lines.push(`'use client'`);
  lines.push(``);

  // Import the table component
  lines.push(`import { ${name}Table } from '@/components/${modelLower}/${name}Table'`);
  lines.push(``);

  // Page component
  lines.push(`export default function ${pluralName}Page() {`);
  lines.push(`  return (`);
  lines.push(`    <div className="container mx-auto py-10">`);
  lines.push(`      <h1 className="text-3xl font-bold mb-6">${pluralName}</h1>`);
  lines.push(`      <${name}Table />`);
  lines.push(`    </div>`);
  lines.push(`  )`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generates a shared layout.tsx for the route group (optional).
 * This can be used to add common UI elements around all generated pages.
 */
export function generateRouteGroupLayout(): string {
  const lines: string[] = [];

  lines.push(`export default function AutoGeneratedLayout({`);
  lines.push(`  children,`);
  lines.push(`}: {`);
  lines.push(`  children: React.ReactNode`);
  lines.push(`}) {`);
  lines.push(`  return <>{children}</>`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
