import { getModels } from "./introspect";
import type { ModelMeta, FieldMeta } from "./types";

/**
 * The shared config format written by the backend CLI and consumed by omni-rest-client.
 * No Prisma dependency on the consumer side — just plain JSON.
 */
export interface OmniRestConfig {
  version: string;
  generatedAt: string;
  models: ModelMeta[];
  zodSchemas: string; // full generated zod schema source (schemas.generated.ts content)
}

/**
 * Generates the omni-rest.config.json content from a Prisma client instance.
 * This is the bridge between the backend (Prisma) and the client CLI (no Prisma).
 */
export function generateConfig(prisma: any): OmniRestConfig {
  const models = getModels(prisma);

  // Inline zod schema generation (avoids circular dep with zod-generator)
  const PRISMA_TO_ZOD: Record<string, string> = {
    String: "z.string()",
    Int: "z.number().int()",
    Float: "z.number()",
    Decimal: "z.number()",
    Boolean: "z.boolean()",
    DateTime: "z.coerce.date()",
    Json: "z.any()",
    BigInt: "z.bigint()",
    Bytes: "z.any()",
  };

  function fieldToZod(field: FieldMeta): string | null {
    if (field.isRelation) return null;
    let zod = PRISMA_TO_ZOD[field.type] ?? "z.any()";
    if (!field.isRequired) zod = `${zod}.optional()`;
    if (field.isList) zod = `z.array(${zod})`;
    return zod;
  }

  const schemaBlocks = models.map((meta) => {
    const createFields = meta.fields
      .filter((f) => !f.isRelation && !f.isId && !f.hasDefaultValue && !f.isUpdatedAt)
      .map((f) => { const z = fieldToZod(f); return z ? `  ${f.name}: ${z},` : null; })
      .filter(Boolean).join("\n");

    const updateFields = meta.fields
      .filter((f) => !f.isRelation && !f.isId && !f.isUpdatedAt)
      .map((f) => {
        const z = fieldToZod(f);
        if (!z) return null;
        const opt = z.includes(".optional()") ? z : `${z}.optional()`;
        return `  ${f.name}: ${opt},`;
      })
      .filter(Boolean).join("\n");

    return `
// ─── ${meta.name} ─────────────────────────────────────────────────────────────

export const ${meta.name}CreateSchema = z.object({
${createFields}
});

export const ${meta.name}UpdateSchema = z.object({
${updateFields}
});

export type ${meta.name}Create = z.infer<typeof ${meta.name}CreateSchema>;
export type ${meta.name}Update = z.infer<typeof ${meta.name}UpdateSchema>;`.trim();
  });

  const zodSchemas = `/**
 * Auto-generated Zod schemas from Prisma schema.
 * Generated by omni-rest — do not edit manually.
 */
import { z } from "zod";

${schemaBlocks.join("\n\n")}
`;

  return {
    version: "1",
    generatedAt: new Date().toISOString(),
    models,
    zodSchemas,
  };
}
