import * as path from "path";
import * as readline from "readline";

import { scanForFrontendDir } from "./frontend/scan";
import { findSchema, loadDMMF } from "./frontend/schema";
import { detectFramework, resolveBaseUrl, resolveOutputDir } from "./frontend/detect";
import { checkDependencies } from "./frontend/deps";
import { buildConfig, type BuildConfigFlags } from "./frontend/prompt";
import { generateHookFile } from "./frontend/codegen/hook";
import { generateColumnsFile } from "./frontend/codegen/columns";
import { generateTableFile } from "./frontend/codegen/table";
import { generateFormFile } from "./frontend/codegen/form";
import { generatePageFile } from "./frontend/codegen/page";
import { generateMenuData } from "./frontend/codegen/menu";
import { generateProvidersFile } from "./frontend/codegen/providers";
import { writeFile, copyBaseComponents, printSummary } from "./frontend/output";
import type { GeneratorConfig, ModelConfig, FileResult } from "./frontend/types";
import { detectProjectStructure } from "./frontend/detect";

// ── ANSI colour helpers (mirrors src/cli.ts COLORS) ──────────────────────────
const COLORS = {
  green:  (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  cyan:   (s: string) => `\x1b[36m${s}\x1b[0m`,
  red:    (s: string) => `\x1b[31m${s}\x1b[0m`,
  bold:   (s: string) => `\x1b[1m${s}\x1b[0m`,
};

// ─────────────────────────────────────────────────────────────────────────────
//  generateAll
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Orchestrates code generation for all models in `config`.
 *
 * For each ModelConfig it calls all four codegen functions, writes the
 * resulting files, then copies the shared base components and prints a
 * summary.
 *
 * For Next.js App Router, also generates page.tsx files and menu-data.ts
 *
 * Requirements: 7.2, 7.3, 7.4, 7.5, 7.6, 15.1, 15.2
 */
export async function generateAll(config: GeneratorConfig): Promise<FileResult[]> {
  const { outputDir, models, framework, frontendDir } = config;
  const generatePages = config.generatePages ?? (framework === "nextjs");
  const generateMenu = config.generateMenu ?? true;
  const routeGroup = config.routeGroup ?? "autogenerated-omni";
  
  // packageRoot is the omni-rest package root (one level up from dist/src)
  const packageRoot = path.resolve(__dirname, "..");

  const results: FileResult[] = [];

  // Detect project structure for Next.js page generation
  const structure = detectProjectStructure(frontendDir);

  for (const modelConfig of models) {
    const { name } = modelConfig.model;
    const modelLower = name.charAt(0).toLowerCase() + name.slice(1);

    // 1. Hook file → {outputDir}/hooks/use{Model}.ts
    const hookContent = generateHookFile(config, modelConfig);
    const hookPath = path.join(outputDir, "hooks", `use${name}.ts`);
    results.push(await writeFile(hookPath, hookContent));

    // 2. Columns file → {outputDir}/components/{model}/{Model}Columns.tsx
    const columnsContent = generateColumnsFile(config, modelConfig);
    const columnsPath = path.join(outputDir, "components", modelLower, `${name}Columns.tsx`);
    results.push(await writeFile(columnsPath, columnsContent));

    // 3. Table file → {outputDir}/components/{model}/{Model}Table.tsx
    const tableContent = generateTableFile(config, modelConfig);
    const tablePath = path.join(outputDir, "components", modelLower, `${name}Table.tsx`);
    results.push(await writeFile(tablePath, tableContent));

    // 4. Form file → {outputDir}/components/{model}/{Model}Form.tsx
    const formContent = generateFormFile(config, modelConfig);
    const formPath = path.join(outputDir, "components", modelLower, `${name}Form.tsx`);
    results.push(await writeFile(formPath, formContent));

    // 5. Next.js App Router page (if enabled and App Router detected)
    if (generatePages && framework === "nextjs" && structure.usesAppRouter && structure.appPath) {
      const pageContent = generatePageFile(config, modelConfig);
      const pluralLower = (name.toLowerCase() + "s");
      const pagePath = path.join(structure.appPath, `(${routeGroup})`, pluralLower, "page.tsx");
      results.push(await writeFile(pagePath, pageContent));
    }
  }

  // Copy shared base components
  const baseResults = await copyBaseComponents(outputDir, packageRoot);
  results.push(...baseResults);

  // Generate QueryClientProvider wrapper for Next.js App Router
  if (framework === "nextjs" && structure.usesAppRouter) {
    const providersContent = generateProvidersFile(config);
    const providersPath = path.join(outputDir, "components", "providers.tsx");
    results.push(await writeFile(providersPath, providersContent));
  }

  // Generate menu-data.ts (if enabled)
  if (generateMenu) {
    const menuContent = generateMenuData(config);
    const menuPath = path.join(outputDir, "lib", "menu-data.ts");
    results.push(await writeFile(menuPath, menuContent));
  }

  // Print summary
  printSummary(results);

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
//  run  (top-level async entry point)
// ─────────────────────────────────────────────────────────────────────────────

const HELP_TEXT = `
  Usage: npx omni-rest generate:frontend [options]

  Options:
    --schema <path>         Path to schema.prisma (default: auto-discover)
    --frontend-dir <path>   Frontend project root (default: auto-scan)
    --out <dir>             Output directory relative to frontend-dir (default: src/)
    --models <names>        Comma-separated model names to generate (default: all)
    --autopilot             Skip all prompts, use defaults
    --no-bulk               Disable bulk delete hooks and wiring
    --no-optimistic         Disable optimistic update patterns
    --no-pages              Disable Next.js page generation (default: enabled for Next.js)
    --no-menu               Disable menu-data.ts generation (default: enabled)
    --route-group <name>    Route group name for Next.js pages (default: autogenerated-omni)
    --stale-time <ms>       useQuery staleTime (default: 30000)
    --gc-time <ms>          useQuery gcTime (default: 300000)
    --steps <mode>          Multi-step form mode: auto | always | never (default: auto)
    --help                  Print this help
`;

/** Prompts the user for a single line of input. */
function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

/**
 * Top-level async entry point for `generate:frontend`.
 *
 * Parses flags from `argv`, runs the full pipeline, and calls `generateAll`.
 *
 * Requirements: 1.1, 2.4, 2.5, 18.1, 18.2, 18.8–18.16
 */
export async function run(argv: string[]): Promise<void> {
  // ── Parse flags ────────────────────────────────────────────────────────────
  let schemaPath: string | undefined;
  let frontendDirFlag: string | undefined;
  let outFlag: string | undefined;
  let modelsFlag: string | undefined;
  let autopilot = false;
  let noBulk = false;
  let noOptimistic = false;
  let generatePages = true;
  let generateMenu = true;
  let routeGroup = "autogenerated-omni";
  let staleTime = 30000;
  let gcTime = 300000;
  let stepsFlag: "auto" | "always" | "never" = "auto";

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case "--help":
        console.log(HELP_TEXT);
        return;
      case "--schema":
        schemaPath = argv[++i];
        break;
      case "--frontend-dir":
        frontendDirFlag = argv[++i];
        break;
      case "--out":
        outFlag = argv[++i];
        break;
      case "--models":
        modelsFlag = argv[++i];
        break;
      case "--autopilot":
        autopilot = true;
        break;
      case "--no-bulk":
        noBulk = true;
        break;
      case "--no-optimistic":
        noOptimistic = true;
        break;
      case "--no-pages":
        generatePages = false;
        break;
      case "--no-menu":
        generateMenu = false;
        break;
      case "--route-group":
        routeGroup = argv[++i];
        break;
      case "--stale-time":
        staleTime = parseInt(argv[++i], 10) || 30000;
        break;
      case "--gc-time":
        gcTime = parseInt(argv[++i], 10) || 300000;
        break;
      case "--steps": {
        const val = argv[++i];
        if (val === "always" || val === "never" || val === "auto") {
          stepsFlag = val;
        }
        break;
      }
    }
  }

  const cwd = process.cwd();

  console.log(COLORS.bold("\n  omni-rest · generate:frontend\n"));

  // ── Step 1: Resolve frontendDir ────────────────────────────────────────────
  let frontendDir: string;

  if (frontendDirFlag) {
    // Requirement 18.1 — use provided path directly
    const resolved = require("path").resolve(cwd, frontendDirFlag);
    const fs = require("fs") as typeof import("fs");
    if (!fs.existsSync(resolved) || !fs.statSync(resolved).isDirectory()) {
      console.error(
        COLORS.red(
          `  ✗ --frontend-dir path does not exist or is not a directory: "${resolved}"`
        )
      );
      process.exit(1);
    }
    frontendDir = resolved;
  } else {
    // Requirement 18.3 — scan for candidates
    const candidates = await scanForFrontendDir(cwd);

    if (candidates.length === 0) {
      // Requirement 18.11 / 18.14
      console.error(
        COLORS.red(
          `  ✗ No frontend project found.\n` +
          `    Scan criteria: next.config.*, vite.config.*, or package.json with react dependency.\n` +
          `    Run from your frontend directory or use --frontend-dir <path>.`
        )
      );
      process.exit(1);
    }

    if (autopilot) {
      if (candidates.length > 1) {
        // Requirement 18.13
        console.error(COLORS.red(`  ✗ Multiple frontend candidates found. Specify one with --frontend-dir:\n`));
        candidates.forEach((c, i) => console.error(`    ${i + 1}. ${c.dir} (score: ${c.score})`));
        process.exit(1);
      }
      // Requirement 18.12 — single candidate, use it
      frontendDir = candidates[0].dir;
      console.log(COLORS.cyan(`  → Using frontend dir: ${frontendDir}`));
    } else if (candidates.length === 1) {
      // Requirement 18.8 / 18.9 — confirm with user
      const answer = await prompt(
        `  Frontend dir detected: ${COLORS.bold(candidates[0].dir)}\n  Use this directory? [Y/n]: `
      );
      if (answer.toLowerCase() === "n" || answer.toLowerCase() === "no") {
        console.log("  Aborted.");
        return;
      }
      frontendDir = candidates[0].dir;
    } else {
      // Requirement 18.10 — multiple candidates, let user pick
      console.log("  Multiple frontend candidates found:\n");
      candidates.forEach((c, i) => {
        console.log(`    ${i + 1}. ${c.dir}  (score: ${c.score}, signals: ${c.signals.join(", ")})`);
      });
      const answer = await prompt(`\n  Select a number [1]: `);
      const idx = (parseInt(answer, 10) || 1) - 1;
      if (idx < 0 || idx >= candidates.length) {
        console.error(COLORS.red("  ✗ Invalid selection."));
        process.exit(1);
      }
      frontendDir = candidates[idx].dir;
    }
  }

  // ── Step 2: Find schema.prisma ─────────────────────────────────────────────
  let resolvedSchemaPath: string;
  try {
    resolvedSchemaPath = await findSchema(cwd, schemaPath);
    console.log(COLORS.cyan(`  → Schema: ${resolvedSchemaPath}`));
  } catch (err: any) {
    console.error(COLORS.red(`  ✗ ${err.message}`));
    process.exit(1);
  }

  // ── Step 3: Load DMMF ──────────────────────────────────────────────────────
  let allModels;
  try {
    allModels = await loadDMMF(frontendDir, resolvedSchemaPath);
    console.log(COLORS.cyan(`  → Found ${allModels.length} model(s): ${allModels.map((m) => m.name).join(", ")}`));
  } catch (err: any) {
    console.error(COLORS.red(`  ✗ ${err.message}`));
    process.exit(1);
  }

  // ── Step 4: Detect framework ───────────────────────────────────────────────
  const framework = detectFramework(frontendDir);
  console.log(COLORS.cyan(`  → Framework: ${framework}`));

  // ── Step 5: Resolve base URL ───────────────────────────────────────────────
  const baseUrl = resolveBaseUrl(frontendDir);
  console.log(COLORS.cyan(`  → Base URL: ${baseUrl}`));

  // ── Step 6: Resolve output dir ─────────────────────────────────────────────
  const outputDir = resolveOutputDir(frontendDir, framework, outFlag);
  console.log(COLORS.cyan(`  → Output dir: ${outputDir}`));

  // ── Step 7: Check dependencies ─────────────────────────────────────────────
  const missing = checkDependencies(frontendDir, framework);
  if (missing.length > 0) {
    console.warn(
      COLORS.yellow(
        `  ⚠ Missing dependencies: ${missing.join(", ")}\n` +
        `    Install with: npm install ${missing.join(" ")}`
      )
    );
  }

  // ── Step 8: Build per-model config ─────────────────────────────────────────
  const modelsFilter = modelsFlag
    ? modelsFlag.split(",").map((s) => s.trim()).filter(Boolean)
    : undefined;

  // Warn about unknown model names in --models filter
  if (modelsFilter) {
    const knownNames = new Set(allModels.map((m) => m.name));
    for (const name of modelsFilter) {
      if (!knownNames.has(name)) {
        console.warn(COLORS.yellow(`  ⚠ Unknown model name in --models filter: "${name}"`));
      }
    }
  }

  const flags: BuildConfigFlags = {
    autopilot,
    noBulk,
    steps: stepsFlag,
    modelsFilter,
  };

  const modelConfigs: ModelConfig[] = await buildConfig(allModels, flags);

  // ── Step 9: Build GeneratorConfig and run generateAll ─────────────────────
  const generatorConfig: GeneratorConfig = {
    frontendDir,
    schemaPath: resolvedSchemaPath,
    framework,
    baseUrl,
    outputDir,
    autopilot,
    models: modelConfigs,
    staleTime,
    gcTime,
    noOptimistic,
    steps: stepsFlag,
    generatePages,
    generateMenu,
    routeGroup,
  };

  await generateAll(generatorConfig);

  console.log(COLORS.bold("\n  Done!\n"));
}
