import { getModels } from "./introspect";
import type { ModelMeta, FieldMeta } from "./types";

/**
 * Maps Prisma scalar types → Zod method names
 */
const PRISMA_TO_ZOD: Record<string, string> = {
  String: "z.string()",
  Int: "z.number().int()",
  Float: "z.number()",
  Decimal: "z.number()",
  Boolean: "z.boolean()",
  DateTime: "z.coerce.date()",
  Json: "z.any()",
  BigInt: "z.bigint()",
  Bytes: "z.any()",
};

/**
 * Converts a single Prisma field to its Zod expression string.
 */
function fieldToZod(field: FieldMeta): string {
  if (field.isRelation) return null as any; // skip relations

  let zod = PRISMA_TO_ZOD[field.type] ?? "z.any()";

  // Optional fields
  if (!field.isRequired) {
    zod = `${zod}.optional()`;
  }

  // List fields
  if (field.isList) {
    zod = `z.array(${zod})`;
  }

  return zod;
}

/**
 * Generates Zod schema source code for a single model.
 *
 * Produces two schemas:
 *   - CreateSchema  — all required fields must be present
 *   - UpdateSchema  — all fields are optional (for PATCH)
 */
function generateModelSchema(meta: ModelMeta): string {
  const name = meta.name;

  const fields = meta.fields
    .filter((f) => !f.isRelation && !f.isId) // skip relations and id (auto)
    .map((f) => {
      const zodExpr = fieldToZod(f);
      if (!zodExpr) return null;
      return `  ${f.name}: ${zodExpr},`;
    })
    .filter(Boolean)
    .join("\n");

  return `
// ─── ${name} ──────────────────────────────────────────────────────────────────

export const ${name}CreateSchema = z.object({
${fields}
});

export const ${name}UpdateSchema = ${name}CreateSchema.partial();

export type ${name}Create = z.infer<typeof ${name}CreateSchema>;
export type ${name}Update = z.infer<typeof ${name}UpdateSchema>;
`.trim();
}

/**
 * Generates a complete Zod schema file for ALL models in your Prisma schema.
 *
 * @example
 * ```ts
 * import { generateZodSchemas } from "omni-rest";
 * const code = generateZodSchemas();
 * fs.writeFileSync("src/schemas.ts", code);
 * ```
 */
export function generateZodSchemas(prisma?: any): string {
  const models = getModels(prisma);

  const schemas = models.map(generateModelSchema).join("\n\n");

  return `/**
 * Auto-generated Zod schemas from Prisma schema.
 * Generated by omni-rest — do not edit manually.
 * Re-run after schema changes.
 */
import { z } from "zod";

${schemas}
`;
}

/**
 * Returns Zod schema OBJECTS at runtime (not source code).
 * Useful for request validation in middleware.
 *
 * Requires "zod" to be installed in the host project.
 */
export function buildRuntimeSchemas(prisma?: any): Record<
  string,
  { create: any; update: any }
> {
  let z: any;
  try {
    z = require("zod").z;
  } catch {
    throw new Error(
      "[omni-rest] zod is required for runtime validation. Run: npm install zod"
    );
  }

  const ZOD_FACTORIES: Record<string, () => any> = {
    String: () => z.string(),
    Int: () => z.number().int(),
    Float: () => z.number(),
    Decimal: () => z.number(),
    Boolean: () => z.boolean(),
    DateTime: () => z.coerce.date(),
    Json: () => z.any(),
    BigInt: () => z.bigint(),
    Bytes: () => z.any(),
  };

  const models = getModels(prisma);
  const result: Record<string, { create: any; update: any }> = {};

  for (const meta of models) {
    const shape: Record<string, any> = {};

    for (const field of meta.fields) {
      if (field.isRelation || field.isId) continue;

      const factory = ZOD_FACTORIES[field.type] ?? (() => z.any());
      let schema = factory();

      if (!field.isRequired) schema = schema.optional();
      if (field.isList) schema = z.array(schema);

      shape[field.name] = schema;
    }

    const createSchema = z.object(shape);
    result[meta.routeName] = {
      create: createSchema,
      update: createSchema.partial(),
    };
  }

  return result;
}